version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio-data:/data
    command: server /data

  trino:
    image: trinodb/trino
    ports:
      - "8080:8080"
    environment:
      - TRINO_CONFIG=/etc/trino
    volumes:
      - ./trino-config:/etc/trino

  dagster:
    image: dagster/dagster-webserver:latest
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster
    volumes:
      - ./dagster:/opt/dagster

  jupyterlab:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  minio-data:
